import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // Existing styles (preserving your current setup)
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    padding: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  backButton: {
    padding: 10,
  },
  backButtonText: {
    fontSize: 24,
    color: '#1E88E5',
    fontFamily: 'DynaPuff',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#333',
    fontFamily: 'DynaPuff-Bold',
    textAlign: 'center',
  },
  settingsButton: {
    padding: 10,
  },
  listContainer: {
    paddingBottom: 20,
  },
  item: {
    backgroundColor: '#FFF',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  itemText: {
    fontSize: 18,
    color: '#333',
    fontFamily: 'DynaPuff',
  },
  quizItemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFF',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  enhancedQuizButton: {
    backgroundColor: '#1E88E5',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  enhancedQuizButtonDisabled: {
    backgroundColor: '#B0BEC5',
  },
  buttonInnerShadow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  enhancedQuizButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontFamily: 'DynaPuff',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
  },
  loadingText: {
    fontSize: 18,
    color: '#333',
    fontFamily: 'DynaPuff',
  },
  quizContainer: {
    flex: 1,
    padding: 20,
    backgroundColor: '#F5F5F5',
  },
  pointsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    padding: 10,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  pointsIcon: {
    fontSize: 20,
    marginRight: 5,
  },
  pointsText: {
    fontSize: 16,
    color: '#333',
    fontFamily: 'DynaPuff',
  },
  progressIndicator: {
    marginBottom: 20,
  },
  progressBar: {
    height: 10,
    backgroundColor: '#E0E0E0',
    borderRadius: 5,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#1E88E5',
  },
  progressText: {
    fontSize: 14,
    color: '#333',
    marginTop: 5,
    textAlign: 'center',
    fontFamily: 'DynaPuff',
  },
  pointsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    padding: 10,
    borderRadius: 15,
    alignSelf: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  pointsValue: {
    fontSize: 16,
    color: '#333',
    fontFamily: 'DynaPuff',
  },
  questionCard: {
    backgroundColor: '#FFF',
    padding: 20,
    borderRadius: 15,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  questionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
    fontFamily: 'DynaPuff-Bold',
  },
  questionText: {
    fontSize: 16,
    color: '#333',
    marginBottom: 10,
    fontFamily: 'DynaPuff',
  },
  timerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timerBar: {
    flex: 1,
    height: 5,
    backgroundColor: '#E0E0E0',
    borderRadius: 5,
    overflow: 'hidden',
    marginRight: 10,
  },
  timerFill: {
    height: '100%',
    backgroundColor: '#1E88E5',
  },
  timerText: {
    fontSize: 14,
    color: '#333',
    fontFamily: 'DynaPuff',
  },
  optionsContainer: {
    marginBottom: 20,
  },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  selectedOption: {
    backgroundColor: '#E3F2FD',
    borderColor: '#1E88E5',
    borderWidth: 2,
  },
  correctOption: {
    backgroundColor: '#C8E6C9',
    borderColor: '#4CAF50',
    borderWidth: 2,
  },
  incorrectOption: {
    backgroundColor: '#FFCDD2',
    borderColor: '#F44336',
    borderWidth: 2,
  },
  optionBadge: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#E0E0E0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  selectedBadge: {
    backgroundColor: '#1E88E5',
  },
  optionBadgeText: {
    fontSize: 16,
    color: '#333',
    fontFamily: 'DynaPuff',
  },
  optionText: {
    fontSize: 16,
    color: '#333',
    flex: 1,
    fontFamily: 'DynaPuff',
  },
  selectedOptionText: {
    color: '#1E88E5',
  },
  feedbackIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
  },
  incorrectIcon: {
    backgroundColor: '#F44336',
  },
  feedbackIconText: {
    fontSize: 16,
    color: '#FFF',
    fontFamily: 'DynaPuff',
  },
  feedbackContainer: {
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 1,
  },
  feedbackText: {
    fontSize: 16,
    fontFamily: 'DynaPuff',
  },
  submitButton: {
    backgroundColor: '#1E88E5',
    paddingVertical: 15,
    borderRadius: 25,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  disabledButton: {
    backgroundColor: '#B0BEC5',
  },
  submitButtonText: {
    fontSize: 18,
    color: '#FFF',
    fontFamily: 'DynaPuff',
  },
  confettiContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '100%',
  },
  confetti: {
    position: 'absolute',
    borderRadius: 5,
  },

  // New styles for RankingScreen
  rankingContainer: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    padding: 20,
  },
  rankingTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#333',
    fontFamily: 'DynaPuff-Bold',
    textAlign: 'center',
    flex: 1,
  },
  placeholder: {
    width: 44, // Match backButton width for centering
  },
  rankingList: {
    paddingBottom: 20,
  },
  rankingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.8)', // Glassmorphism
    padding: 15,
    borderRadius: 15,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  currentUserCard: {
    backgroundColor: 'rgba(227, 242, 253, 0.8)', // Light blue for current user
    borderColor: '#1E88E5',
    borderWidth: 2,
  },
  rankContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 60,
  },
  rankText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    fontFamily: 'DynaPuff-Bold',
  },
  badgeIcon: {
    marginLeft: 5,
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 18,
    color: '#333',
    fontFamily: 'DynaPuff',
  },
  currentUserName: {
    color: '#1E88E5',
    fontWeight: 'bold',
  },
  scoreText: {
    fontSize: 14,
    color: '#666',
    fontFamily: 'DynaPuff',
  },
});