import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: '#f0f4f8',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f0f4f8',
  },
  loadingText: {
    fontFamily: 'DynaPuff',
    fontSize: 20,
    color: '#4b86f0',
  },
  quizContainer: {
    flex: 1,
    backgroundColor: '#f0f4f8',
    padding: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingTop: 15,
    marginBottom: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#e0e9fa',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    fontSize: 24,
    color: '#4b86f0',
  },
  settingsButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#e0e9fa',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pointsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
    marginRight: 20,
    marginBottom: 15,
  },
  pointsIcon: {
    fontSize: 20,
    marginRight: 5,
  },
  pointsText: {
    fontFamily: 'DynaPuff',
    fontSize: 16,
    color: '#4b86f0',
  },
  title: {
    fontFamily: 'DynaPuff-Bold',
    fontSize: 28,
    marginBottom: 20,
    textAlign: 'center',
    color: '#4b86f0',
  },
  progressIndicator: {
    marginBottom: 15,
  },
  progressBar: {
    height: 8,
    backgroundColor: '#e0e0e0',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 5,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#4b86f0',
    borderRadius: 4,
  },
  progressText: {
    fontFamily: 'DynaPuff',
    fontSize: 14,
    color: '#666',
    textAlign: 'right',
  },
  pointsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#fff8e1',
    borderRadius: 15,
    paddingVertical: 5,
    paddingHorizontal: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  pointsValue: {
    fontFamily: 'DynaPuff-Bold',
    fontSize: 18,
    color: '#ff6f9c',
  },
  questionCard: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 4,
  },
  questionTitle: {
    fontFamily: 'DynaPuff-Bold',
    fontSize: 20,
    color: '#ff6f9c',
    marginBottom: 10,
  },
  questionText: {
    fontFamily: 'DynaPuff',
    fontSize: 18,
    color: '#333',
    marginBottom: 15,
    lineHeight: 26,
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timerBar: {
    flex: 1,
    height: 6,
    backgroundColor: '#eee',
    borderRadius: 3,
    overflow: 'hidden',
    marginRight: 10,
  },
  timerFill: {
    height: '100%',
    backgroundColor: '#ffb347',
    borderRadius: 3,
  },
  timerText: {
    fontFamily: 'DynaPuff',
    fontSize: 14,
    color: '#666',
    width: 40,
    textAlign: 'right',
  },
  optionsContainer: {
    marginBottom: 20,
  },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 12,
    marginBottom: 12,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  selectedOption: {
    borderColor: '#4b86f0',
    backgroundColor: '#ebf3ff',
  },
  correctOption: {
    borderColor: '#4CAF50',
    backgroundColor: '#ebfbef',
  },
  incorrectOption: {
    borderColor: '#F44336',
    backgroundColor: '#feeced',
  },
  optionBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#e0e0e0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  selectedBadge: {
    backgroundColor: '#4b86f0',
  },
  optionBadgeText: {
    fontFamily: 'DynaPuff-Bold',
    fontSize: 16,
    color: '#666',
  },
  selectedOptionText: {
    color: '#4b86f0',
  },
  optionText: {
    fontFamily: 'DynaPuff',
    fontSize: 16,
    color: '#333',
    flex: 1,
  },
  feedbackIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  incorrectIcon: {
    backgroundColor: '#F44336',
  },
  feedbackIconText: {
    fontFamily: 'DynaPuff-Bold',
    fontSize: 16,
    color: 'white',
  },
  feedbackContainer: {
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
    borderWidth: 1,
  },
  feedbackText: {
    fontFamily: 'DynaPuff',
    fontSize: 16,
    textAlign: 'center',
  },
  submitButton: {
    height: 56,
    borderRadius: 28,
    backgroundColor: '#4b86f0',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  disabledButton: {
    backgroundColor: '#a3c2f8',
  },
  buttonInnerShadow: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitButtonText: {
    fontFamily: 'DynaPuff-Bold',
    fontSize: 18,
    color: 'white',
    textAlign: 'center',
  },
  confettiContainer: {
    ...StyleSheet.absoluteFillObject,
    pointerEvents: 'none',
  },
  confetti: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  // Subject styles
  subjectCard: {
    borderRadius: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
    overflow: 'hidden',
  },
  subjectCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
  },
  levelBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  levelText: {
    fontFamily: 'DynaPuff-Bold',
    fontSize: 18,
    color: 'white',
  },
  subjectInfo: {
    flex: 1,
  },
  subjectName: {
    fontFamily: 'DynaPuff-Bold',
    fontSize: 18,
    color: '#333',
    marginBottom: 8,
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: '#e0e0e0',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 5,
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  statusIconContainer: {
    marginLeft: 10,
  },
  statusIcon: {
    fontSize: 24,
  },
  quizImageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
  },
  quizImage: {
    width: 150,
    height: 150,
    resizeMode: 'contain',
  },
  listContainer: {
    padding: 20,
  },
  quizItemContainer: {
    marginBottom: 16,
  },
  item: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#f5f5f5',
    marginBottom: 8,
  },
  itemText: {
    fontFamily: 'DynaPuff',
    fontSize: 17,
    color: '#2c3e50',
    padding: 14,
    lineHeight: 24,
  },
  enhancedQuizButton: {
    height: 60,
    width: 250,
    borderRadius: 30,
    justifyContent: 'center',
    backgroundColor: '#4285F4',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 2,
    borderColor: '#000000',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 0,
    elevation: 5,
  },
  enhancedQuizButtonDisabled: {
    backgroundColor: '#e0e0e0',
    shadowOpacity: 0.1,
    elevation: 2,
  },
  enhancedQuizButtonText: {
    fontFamily: 'DynaPuff',
    fontSize: 16,
    color: 'white',
    fontWeight: 'bold',
  },

  container: { flex: 1, backgroundColor: '#f0f4f8' },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#f0f4f8' },
  loadingText: { fontFamily: 'DynaPuff', fontSize: 20, color: '#4b86f0' },
  quizContainer: { flex: 1, backgroundColor: '#f0f4f8', padding: 16 },
  header: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 15, paddingTop: 15, marginBottom: 10 },
  backButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#e0e9fa', justifyContent: 'center', alignItems: 'center' },
  backButtonText: { fontSize: 24, color: '#4b86f0' },
  settingsButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#e0e9fa', justifyContent: 'center', alignItems: 'center' },
  logoContainer: { alignItems: 'center', marginTop: 20, paddingHorizontal: 20 },
  subjectTitle: { fontFamily: 'DynaPuff-Bold', fontSize: 20, color: '#4b86f0', textAlign: 'center', marginBottom: 15, textShadowColor: 'rgba(0, 0, 0, 0.5)', textShadowOffset: { width: 1, height: 1 }, textShadowRadius: 1, borderColor: '#000' },
  computerImage: { width: 320, height: 120, resizeMode: 'contain', marginBottom: 20 },
  lessonContainer: { paddingHorizontal: 20, alignItems: 'center' },
  lessonButtonWrapper: { width: '100%', marginBottom: 15 },
  listContainer: { padding: 20 },
  title: { fontFamily: 'DynaPuff-Bold', fontSize: 28, marginBottom: 20, textAlign: 'center', color: '#4b86f0' },
  item: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 15, backgroundColor: '#fff', borderRadius: 15, marginBottom: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 3, elevation: 3 },
  itemText: { fontFamily: 'DynaPuff', fontSize: 18, color: '#333', flex: 1, marginRight: 10 },
  progressIndicator: { marginBottom: 15 },
  progressBar: { height: 8, backgroundColor: '#e0e0e0', borderRadius: 4, overflow: 'hidden', marginBottom: 5 },
  progressFill: { height: '100%', backgroundColor: '#4b86f0', borderRadius: 4 },
  pointsCard: { flexDirection: 'row', alignItems: 'center', alignSelf: 'center', backgroundColor: '#FFEB3B', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 20, marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 3, elevation: 3 },
  pointsContainer: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-end', marginRight: 20, marginBottom: 15 },
  pointsIcon: { fontSize: 20, marginRight: 5 },
  pointsText: { fontFamily: 'DynaPuff', fontSize: 16, color: '#4b86f0' },
  pointsValue: { fontFamily: 'DynaPuff-Bold', fontSize: 18, color: '#212121' },
  questionCard: { backgroundColor: 'white', borderRadius: 15, padding: 20, marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.15, shadowRadius: 5, elevation: 5 },
  questionTitle: { fontFamily: 'DynaPuff-Bold', fontSize: 22, color: '#333', marginBottom: 15 },
  questionText: { fontFamily: 'DynaPuff', fontSize: 18, color: '#333', lineHeight: 26, marginBottom: 20 },
  timerContainer: { flexDirection: 'row', alignItems: 'center' },
  timerBar: { flex: 1, height: 6, backgroundColor: '#e0e0e0', borderRadius: 3, marginRight: 10, overflow: 'hidden' },
  timerFill: { height: '100%', backgroundColor: '#4CAF50', borderRadius: 3 },
  timerText: { fontFamily: 'DynaPuff', fontSize: 14, color: '#757575' },
  optionsContainer: { marginBottom: 20 },
  optionCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'white', borderRadius: 15, padding: 15, marginBottom: 12, borderWidth: 2, borderColor: '#e0e0e0', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 3, elevation: 2 },
  selectedOption: { borderColor: '#4b86f0', backgroundColor: '#e6f0ff' },
  correctOption: { borderColor: '#4CAF50', backgroundColor: '#e8f5e9' },
  incorrectOption: { borderColor: '#F44336', backgroundColor: '#ffebee' },
  optionBadge: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#f0f0f0', justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  selectedBadge: { backgroundColor: '#4b86f0' },
  optionBadgeText: { fontFamily: 'DynaPuff-Bold', fontSize: 16, color: '#757575' },
  optionText: { fontFamily: 'DynaPuff', fontSize: 16, color: '#333', flex: 1 },
  selectedOptionText: { color: '#4b86f0' },
  feedbackIcon: { width: 24, height: 24, borderRadius: 12, backgroundColor: '#4CAF50', justifyContent: 'center', alignItems: 'center' },
  incorrectIcon: { backgroundColor: '#F44336' },
  feedbackIconText: { color: 'white', fontWeight: 'bold', fontSize: 14 },
  feedbackContainer: { padding: 15, borderRadius: 10, marginBottom: 20, borderWidth: 1 },
  feedbackText: { fontFamily: 'DynaPuff', fontSize: 16, textAlign: 'center' },
  submitButton: { height: 60, borderRadius: 30, backgroundColor: '#4CAF50', justifyContent: 'center', alignItems: 'center', marginTop: 10, overflow: 'hidden' },
  submitButtonText: { fontFamily: 'DynaPuff-Bold', fontSize: 18, color: 'white' },
  confettiContainer: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, pointerEvents: 'none' },
  confetti: { position: 'absolute', width: 10, height: 10, borderRadius: 5 },
  subjectCard: { borderRadius: 15, marginBottom: 15, shadowColor: '#000', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.15, shadowRadius: 5, elevation: 4, overflow: 'hidden' },
  subjectCardContent: { flexDirection: 'row', alignItems: 'center', padding: 20 },
  levelBadge: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  levelText: { fontFamily: 'DynaPuff-Bold', fontSize: 18, color: 'white' },
  subjectInfo: { flex: 1 },
  subjectName: { fontFamily: 'DynaPuff-Bold', fontSize: 18, color: '#333', marginBottom: 8 },
  progressBarContainer: { height: 8, backgroundColor: '#e0e0e0', borderRadius: 4, overflow: 'hidden', marginBottom: 5 },
  progressBarFill: { height: '100%', borderRadius: 4 },
  progressText: { fontFamily: 'DynaPuff', fontSize: 12, color: '#757575' },
  statusIconContainer: { marginLeft: 10 },
  statusIcon: { fontSize: 24 },
  quizItemContainer: { marginBottom: 16 },
  item: { backgroundColor: '#ffffff', borderRadius: 12, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 3, elevation: 3, borderWidth: 1, borderColor: '#f5f5f5', marginBottom: 8 },
  itemText: { fontFamily: 'DynaPuff', fontSize: 17, color: '#2c3e50', padding: 14, lineHeight: 24 },
  enhancedQuizButton: { height: 60, width: 250, borderRadius: 30, justifyContent: 'center', backgroundColor: '#4285F4', alignItems: 'center', marginBottom: 20, borderWidth: 2, borderColor: '#000000', shadowColor: '#000', shadowOffset: { width: 4, height: 5 }, shadowOpacity: 0.5, shadowRadius: 0, elevation: 5 },
  enhancedQuizButtonDisabled: { backgroundColor: '#e0e0e0', shadowOpacity: 0.1, elevation: 2 },
  enhancedQuizButtonText: { fontFamily: 'DynaPuff', fontSize: 16, color: 'white', fontWeight: 'bold' },
  quizImageContainer: { alignItems: 'center', justifyContent: 'center', marginVertical: 20 },
  quizImage: { width: 150, height: 150, resizeMode: 'contain' },
  disabledButton: { backgroundColor: '#a3c2f8' },
  buttonInnerShadow: { width: '100%', height: '100%', justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 5, height: 4 }, shadowOpacity: 0.3, shadowRadius: 2, elevation: 5 },
});